// export_to_frontend.js
// Run: node scripts/export_to_frontend.js
const fs = require('fs');
const path = require('path');

const db = JSON.parse(fs.readFileSync(path.join(__dirname, '../output/icd10_insurance_database_v1.json'), 'utf-8'));

const lines = [];
lines.push(`// AUTO-GENERATED by export_to_frontend.js — DO NOT EDIT MANUALLY`);
lines.push(`// Source: icd-database/output/icd10_insurance_database_v1.json`);
lines.push(`// Generated: ${new Date().toISOString()}`);
lines.push(``);
lines.push(`export interface ICDVariant {`);
lines.push(`  code: string;`);
lines.push(`  description: string;`);
lines.push(`  use_when: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`export interface ICDAssociated {`);
lines.push(`  code: string;`);
lines.push(`  description: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`export interface ICDCondition {`);
lines.push(`  id: string;`);
lines.push(`  specialty: string;`);
lines.push(`  condition_name: string;`);
lines.push(`  keywords: string[];`);
lines.push(`  primary_code: string;`);
lines.push(`  primary_description: string;`);
lines.push(`  variants: ICDVariant[];`);
lines.push(`  associated_codes: ICDAssociated[];`);
lines.push(`  admission_criteria: string[];`);
lines.push(`  los: { min: number; typical: number; icu_days: number; note: string };`);
lines.push(`  expected_procedures: string[];`);
lines.push(`  tpa_query_triggers: string[];`);
lines.push(`  must_include_docs: string[];`);
lines.push(`  india_notes: string;`);
lines.push(`  pmjay_eligible: boolean;`);
lines.push(`  package_rate_available: boolean;`);
lines.push(`}`);
lines.push(``);
lines.push(`export const ICD_CONDITIONS: ICDCondition[] = [`);

db.conditions.forEach((c, idx) => {
    const comma = idx < db.conditions.length - 1 ? ',' : '';
    const obj = {
        id: c.id,
        specialty: c.specialty,
        condition_name: c.condition_name,
        keywords: c.keywords || [],
        primary_code: c.icd_codes.primary.code,
        primary_description: c.icd_codes.primary.description || '',
        variants: (c.icd_codes.specific_variants || []).map(v => ({
            code: v.code,
            description: v.description || '',
            use_when: v.use_when || ''
        })),
        associated_codes: (c.icd_codes.associated_codes || []).map(a => ({
            code: a.code,
            description: a.description || ''
        })),
        admission_criteria: (c.admission_criteria || []).slice(0, 6),
        los: {
            min: c.expected_length_of_stay?.minimum_days || 3,
            typical: c.expected_length_of_stay?.typical_days || 5,
            icu_days: c.expected_length_of_stay?.icu_days_if_applicable || 0,
            note: c.expected_length_of_stay?.note || ''
        },
        expected_procedures: (c.expected_procedures || []).slice(0, 6),
        tpa_query_triggers: (c.tpa_query_triggers || []).slice(0, 4),
        must_include_docs: (c.must_include_in_documentation || []).slice(0, 6),
        india_notes: c.india_specific_notes || '',
        pmjay_eligible: !!c.pmjay_eligible,
        package_rate_available: !!c.package_rate_available,
    };
    lines.push(`  ${JSON.stringify(obj)}${comma}`);
});

lines.push(`];`);
lines.push(``);

// Build a flat ICD10Entry list from primary + variants for backward compat searchICD10
lines.push(`// ── Backward-compatible flat list (primary codes only) ──`);
lines.push(`export interface ICD10Entry { code: string; description: string; commonName?: string; specialty?: string; }`);
lines.push(``);
lines.push(`export const ICD10_DATABASE: ICD10Entry[] = ICD_CONDITIONS.map(c => ({`);
lines.push(`  code: c.primary_code,`);
lines.push(`  description: c.primary_description,`);
lines.push(`  commonName: c.condition_name,`);
lines.push(`  specialty: c.specialty,`);
lines.push(`}));`);
lines.push(``);

// searchICD10 - backward compat
lines.push(`export const searchICD10 = (query: string): ICD10Entry[] => {`);
lines.push(`  if (!query || query.length < 2) return [];`);
lines.push(`  const q = query.toLowerCase();`);
lines.push(`  const seen = new Set<string>();`);
lines.push(`  const results: ICD10Entry[] = [];`);
lines.push(`  for (const c of ICD_CONDITIONS) {`);
lines.push(`    const hit = c.primary_code.toLowerCase().includes(q)`);
lines.push(`      || c.condition_name.toLowerCase().includes(q)`);
lines.push(`      || c.primary_description.toLowerCase().includes(q)`);
lines.push(`      || c.keywords.some(k => k.toLowerCase().includes(q));`);
lines.push(`    if (hit && !seen.has(c.primary_code)) {`);
lines.push(`      seen.add(c.primary_code);`);
lines.push(`      results.push({ code: c.primary_code, description: c.primary_description, commonName: c.condition_name, specialty: c.specialty });`);
lines.push(`    }`);
lines.push(`    if (results.length >= 12) break;`);
lines.push(`  }`);
lines.push(`  return results;`);
lines.push(`};`);
lines.push(``);

// getConditionByCode
lines.push(`export const getConditionByCode = (code: string): ICDCondition | undefined =>`);
lines.push(`  ICD_CONDITIONS.find(c => c.primary_code === code || c.variants.some(v => v.code === code));`);
lines.push(``);

// getConditionByName - fuzzy
lines.push(`export const getConditionByName = (name: string): ICDCondition | undefined => {`);
lines.push(`  const q = name.toLowerCase();`);
lines.push(`  return ICD_CONDITIONS.find(c =>`);
lines.push(`    c.condition_name.toLowerCase().includes(q) || c.keywords.some(k => k.toLowerCase().includes(q)));`);
lines.push(`};`);
lines.push(``);

// suggestICD - ranked
lines.push(`export interface ICDSuggestion {`);
lines.push(`  condition: ICDCondition;`);
lines.push(`  confidence: number;`);
lines.push(`  matchReason: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`export const suggestICD = (query: string, maxResults = 5): ICDSuggestion[] => {`);
lines.push(`  if (!query || query.length < 2) return [];`);
lines.push(`  const q = query.toLowerCase();`);
lines.push(`  const scored: ICDSuggestion[] = [];`);
lines.push(`  for (const c of ICD_CONDITIONS) {`);
lines.push(`    let score = 0; let reason = '';`);
lines.push(`    if (c.condition_name.toLowerCase() === q) { score = 1.0; reason = 'Exact match'; }`);
lines.push(`    else if (c.condition_name.toLowerCase().startsWith(q)) { score = 0.9; reason = 'Name starts with query'; }`);
lines.push(`    else if (c.condition_name.toLowerCase().includes(q)) { score = 0.8; reason = 'Name contains query'; }`);
lines.push(`    else if (c.primary_code.toLowerCase().includes(q)) { score = 0.85; reason = 'ICD code match'; }`);
lines.push(`    else if (c.primary_description.toLowerCase().includes(q)) { score = 0.75; reason = 'Description match'; }`);
lines.push(`    else if (c.keywords.some(k => k.toLowerCase().includes(q))) { score = 0.65; reason = 'Keyword/Hinglish match'; }`);
lines.push(`    if (score > 0) scored.push({ condition: c, confidence: score, matchReason: reason });`);
lines.push(`  }`);
lines.push(`  return scored.sort((a, b) => b.confidence - a.confidence).slice(0, maxResults);`);
lines.push(`};`);

const output = lines.join('\n');
const outPath = path.join(__dirname, '../../opdv3/config/icd10Database.ts');
fs.writeFileSync(outPath, output, 'utf-8');

const kb = (output.length / 1024).toFixed(1);
console.log(`✅ Written to ${outPath}`);
console.log(`   ${db.conditions.length} conditions | ${kb} KB`);
